name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # todo: switch to v2
      - run: yarn test
      # - run: npm run start
      # - run: npm run format-check
      # - run: npm run lint
      # - run: npm run pack
      # - run: npm run gendocs
      # - run: npm test
